#!/bin/sh

GIT=/home/grobe0ba/opt/mars/bin/git
REPO_PATH=/var/trac/git

exec >/dev/null 2>&1

rm -rf $REPO_PATH
$GIT init --bare /var/trac/git
ln -s /var/trac/post-receive /var/trac/git/hooks/post-receive
